services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: "bash"
    volumes:
      - .:/app
      - ./config/certificate.crt:/secrets/certificate.crt:ro
      - ./config/certificate.key:/secrets/certificate.key:ro
    entrypoint: ./entrypoint.sh
    env_file: 
      - .env
