FROM elixir:1.15

RUN apt-get update && \
    apt-get install -y inotify-tools && \
    mix local.hex --force && \
    mix archive.install hex phx_new --force && \
    mix local.rebar --force

ENV APP_HOME /app

RUN mkdir $APP_HOME

WORKDIR $APP_HOME
